project:
  type: book
  output-dir: "../templates/docs/"

book:
  title: "DICE documentation"
  # author: "Norah Jones"
  date: "10/3/2024"
  chapters:
    - index.qmd
    - stimuli.qmd
    - dice-app.qmd
    - deployment.qmd
    - data.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



