project:
  type: book
  output-dir: "../templates/docs/"

book:
  title: "DICE Documentation"
  date: "10/30/2024"
  chapters:
    - index.qmd
    - cases.qmd
    - stimuli.qmd
    - dice-app.qmd
    - deployment.qmd
    - data.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    execute:
      echo: false
      warning: false
  pdf:
    documentclass: scrreprt



