project:
  type: book
  output-dir: "../templates/docs/"

book:
  title: "Documentation"
  date: "10/30/2024"
  chapters:
    - index.qmd
    - cases.qmd
    - stimuli.qmd
    - dice-app.qmd
    - data.qmd
    - deployment.qmd
    - references.qmd
  navbar: 
    logo: "dice-logo.png"
    logo-href: https://www.dice-app.org/

bibliography: references.bib

format:
  html:
    theme: cosmo
    execute:
      echo: false
      warning: false
  pdf:
    documentclass: scrreprt



