<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.132">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Documentation - 1&nbsp; Case Studies</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./stimuli.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="https://www.dice-app.org/" class="navbar-brand navbar-brand-logo">
    <img src="./dice-logo-white.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Documentation</span>
    </a>
  </div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Case Studies</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cases.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Case Studies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stimuli.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Stimuli</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dice-app.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Launch a Study</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./deployment.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Deploy DICE yourself</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-positioning-case" id="toc-sec-positioning-case" class="nav-link active" data-scroll-target="#sec-positioning-case"><span class="toc-section-number">1.1</span>  Case Study 1: When Do Users Remember Ads? Dwell Time Outperforms Position in Explaining Recall</a>
  <ul class="collapse">
  <li><a href="#experimental-design" id="toc-experimental-design" class="nav-link" data-scroll-target="#experimental-design"><span class="toc-section-number">1.1.1</span>  Experimental Design</a></li>
  <li><a href="#procedure" id="toc-procedure" class="nav-link" data-scroll-target="#procedure"><span class="toc-section-number">1.1.2</span>  Procedure</a></li>
  <li><a href="#stimuli" id="toc-stimuli" class="nav-link" data-scroll-target="#stimuli"><span class="toc-section-number">1.1.3</span>  Stimuli</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="toc-section-number">1.1.4</span>  Data</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis"><span class="toc-section-number">1.1.5</span>  Analysis</a></li>
  </ul></li>
  <li><a href="#sec-brand-safety-case" id="toc-sec-brand-safety-case" class="nav-link" data-scroll-target="#sec-brand-safety-case"><span class="toc-section-number">1.2</span>  Case Study 2: When Does Context Harm Brands? Manipulating Feed Composition to Study Brand Safety</a>
  <ul class="collapse">
  <li><a href="#experimental-design-1" id="toc-experimental-design-1" class="nav-link" data-scroll-target="#experimental-design-1"><span class="toc-section-number">1.2.1</span>  Experimental Design</a></li>
  <li><a href="#procedure-1" id="toc-procedure-1" class="nav-link" data-scroll-target="#procedure-1"><span class="toc-section-number">1.2.2</span>  Procedure</a></li>
  <li><a href="#stimuli-1" id="toc-stimuli-1" class="nav-link" data-scroll-target="#stimuli-1"><span class="toc-section-number">1.2.3</span>  Stimuli</a></li>
  <li><a href="#participants-and-randomization-checks" id="toc-participants-and-randomization-checks" class="nav-link" data-scroll-target="#participants-and-randomization-checks"><span class="toc-section-number">1.2.4</span>  Participants and Randomization Checks</a></li>
  <li><a href="#data-1" id="toc-data-1" class="nav-link" data-scroll-target="#data-1"><span class="toc-section-number">1.2.5</span>  Data</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-cases" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Case Studies</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="sec-positioning-case" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="sec-positioning-case"><span class="header-section-number">1.1</span> Case Study 1: When Do Users Remember Ads? Dwell Time Outperforms Position in Explaining Recall</h2>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<p>While investigating which content <em>cuts through the clutter</em> <span class="citation" data-cites="Ordenes_2019">(<a href="references.html#ref-Ordenes_2019" role="doc-biblioref">Ordenes et al. 2019</a>)</span>, we focus on the content’s position rather than examining a sponsored post’s characteristics <span class="citation" data-cites="BergerMoeSchweidel_2023">(see, e.g., <a href="references.html#ref-BergerMoeSchweidel_2023" role="doc-biblioref">Berger, Moe, and Schweidel 2023</a> who study the content’s linguistic features)</span>. Specifically, we examine whether a sponsored post’s position in a social media feed affects its recall, building on research about recency and primacy effects <span class="citation" data-cites="WedelPieters_2000 MurphyHofackerMizerski_2006 AgarwalHosanagarSmith_2011">(see, e.g., <a href="references.html#ref-WedelPieters_2000" role="doc-biblioref">Wedel and Pieters 2000</a>; <a href="references.html#ref-MurphyHofackerMizerski_2006" role="doc-biblioref">Murphy, Hofacker, and Mizerski 2006</a>; <a href="references.html#ref-AgarwalHosanagarSmith_2011" role="doc-biblioref">Agarwal, Hosanagar, and Smith 2011</a>)</span>. A naïve model reveals a primacy effect, where sponsored posts in higher positions show increased likelihood of recall. However, this effect disappears when controlling for dwell time. Furthermore, our analysis demonstrates that longer dwell times correlate with higher recall probability for sponsored posts.</p>
<p>Using position effects in social media advertising as an illustrative example, the primary goal of this case study is to demonstrate practical applications of the DICE app’s dwell time measurement. By showing how to create a feed and then link post-specific dwell times with self-reported recall measures, we provide a practical template for researchers who intend to combine DICE’s behavioral measures with survey data elicited in tools such as Qualtrics.</p>
<section id="experimental-design" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="experimental-design"><span class="header-section-number">1.1.1</span> Experimental Design</h3>
<p>To investigate the relationship between ad placement and recall, we simulated <a href="https://perma.cc/87B9-H6ZV" target="_blank">social media feeds</a> containing both organic and sponsored posts. Whereas the set of organic and sponsored posts was the same for all participants, the sequence in which the participants were exposed to these posts was unique for every participant as we randomized the sequence between subjects.</p>
<p>Aiming to create ecologically valid stimuli, we populated our experimental feed with thrity-five memes (organic posts) and five consumer electronics advertisements (sponsored posts). Accordingly, we collected memes from <em>9gag</em>, a popular account with more than sixteen million followers on X (formerly called “Twitter”) that is well known for its internet meme collections. The choice of memes as organic content was deliberate, given their dominant role in social media engagement, particularly among younger users: <span class="citation" data-cites="MalodiaEtAl_2022">Malodia et al. (<a href="references.html#ref-MalodiaEtAl_2022" role="doc-biblioref">2022</a>)</span> report that 75% of social media users aged 13 to 36 regularly share memes, and 30% of these users share memes daily, with Instagram users sharing over 1 million meme-related posts per day in 2020 <span class="citation" data-cites="Instagram_2020">(<a href="references.html#ref-Instagram_2020" role="doc-biblioref">Instagram 2020</a>)</span>. This prevalence of meme consumption among younger demographics informed both our recruiting strategy and our selection of sponsored content: we recruited 300 young American participants (<span class="math inline">\(M_{age}\)</span>=29.42 years; 53% female) from Prolific and selected consumer electronics advertisements from established brands (i.e., Apple, Bose, Nintendo, Samsung, Whoop) retrieved from Facebook’s Ad Library–a publicly accessible database that archives advertisements running across Meta’s platforms. The selected sponsored posts showed natural variation in their characteristics, reflecting the diversity of ads users encounter in their daily social media use. This approach aligns with recent methodological work on stimulus sampling <span class="citation" data-cites="SimonsohnEtAl_2024">(<a href="references.html#ref-SimonsohnEtAl_2024" role="doc-biblioref">Simonsohn, Montealegre, and Evangelidis 2024</a>)</span> which demonstrates that in studies focused on a single manipulated variable (a sponsored post’s position in our case), using diverse stimuli helps ensure effects are not driven by idiosyncratic characteristics of any particular advertisement, increasing both internal and ecological validity.</p>
<div class="cell">

</div>
<p><a href="#fig-design">Figure&nbsp;<span>1.1</span></a> provides a visual representation of our experimental design, specifically illustrating the randomization of sponsored post positions across participants. The figure plots the position in feed against 15 randomly sampled participants, with different colors representing the five brands. <a href="#fig-design">Figure&nbsp;<span>1.1</span></a> demonstrates how the sponsored posts’ positions were randomly distributed throughout the feed, ensuring that each participant encountered the five advertisements in a unique sequence with no systematic patterns in the placement of any particular brand’s advertisements.</p>
<div class="cell-output-display">
<div id="fig-design" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="cases_files/figure-html/fig-design-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1.1: Randomized Placement of Sponsored Posts Across Participants’ Feeds</figcaption><p></p>
</figure>
</div>
</div>
</section>
<section id="procedure" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="procedure"><span class="header-section-number">1.1.2</span> Procedure</h3>
<div class="cell">

</div>
<p>Participants browsed the simulated feed on their own devices (72% Desktop, 25% Mobile, and 3% Tablet), allowing for unobtrusive measurement of dwell time for each post. After scrolling through the feed, we redirected participants to a Qualtrics survey in which they first provided demographic information as a filler task. Subsequently, we measured whether participants recalled seeing the ads by the five brands in the feed. Specifically, we measured cued recall for which we showed participants a list of twenty brands from different categories and asked them to indicate whether they recalled seeing them <span class="citation" data-cites="CampbellKeller_2003 SimonovVallettiVeiga_2024">(see, e.g., <a href="references.html#ref-CampbellKeller_2003" role="doc-biblioref">Campbell and Keller 2003</a>; <a href="references.html#ref-SimonovVallettiVeiga_2024" role="doc-biblioref">Simonov, Valletti, and Veiga 2024</a>)</span>. We also included a no-recall option. Finally, participants read a debriefing and were redirected to Prolific.</p>
</section>
<section id="stimuli" class="level3" data-number="1.1.3">
<h3 data-number="1.1.3" class="anchored" data-anchor-id="stimuli"><span class="header-section-number">1.1.3</span> Stimuli</h3>
<p>We next illustrate how we configured the feed to match our experimental design. Specifically, we created a CSV file that contains forty rows where each row represents one unique post. To guarantee that the order in which the posts were displayed was randomized between participants, we left the <code>&lt;sequence&gt;</code> column empty. Whenever the DICE app encounters missing values in that column, it assigns random numbers to that cell. Hence, leaving some, or in our case, <em>all</em> cells of this column empty, leads to random numbers and thus, random sequences in which the posts are displayed. Next, we specified the Boolean <code>&lt;sponsored&gt;</code> column and assigned a 0 to all thirty-five organic posts and a 1 to the five sponsored posts. For these sponsored posts, we also specified a <code>&lt;target&gt;</code> which is the URL of landing page participants are directed to if they click on the corresponding sponsored post. As a final step, we uploaded the CSV file to an online repository to create a URL that can be passed to DICE’s web app.</p>
<p><a href="#tbl-stimuli-case-1">Table&nbsp;<span>1.1</span></a> shows an excerpt of the exact CSV files we used to create the stimuli for this study. You can download that file <a href="https://raw.githubusercontent.com/Howquez/DICE/refs/heads/main/studies/meme_feed/stimuli/9gag.csv" target="_blank">here</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-stimuli-case-1" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;1.1: CSV File Used in Study 1</caption>
<colgroup>
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 9%">
<col style="width: 24%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 16%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">doc_id</th>
<th style="text-align: left;">datetime</th>
<th style="text-align: left;">text</th>
<th style="text-align: left;">media</th>
<th style="text-align: left;">alt_text</th>
<th style="text-align: right;">likes</th>
<th style="text-align: right;">reposts</th>
<th style="text-align: right;">replies</th>
<th style="text-align: left;">username</th>
<th style="text-align: left;">handle</th>
<th style="text-align: left;">user_description</th>
<th style="text-align: left;">user_image</th>
<th style="text-align: right;">user_followers</th>
<th style="text-align: right;">commented_post</th>
<th style="text-align: right;">sponsored</th>
<th style="text-align: left;">target</th>
<th style="text-align: left;">condition</th>
<th style="text-align: left;">sequence</th>
<th style="text-align: left;">source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">34</td>
<td style="text-align: left;">20.09.24 12:01</td>
<td style="text-align: left;">Dental receptionist when you don’t know if you’ll be free at 2:30pm next February</td>
<td style="text-align: left;">https://pbs.twimg.com/media/GX3wITOX0AAEyhO?format=jpg&amp;name=4096x4096</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">247</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">9GAG ❤️ Memeland</td>
<td style="text-align: left;">9GAG</td>
<td style="text-align: left;">Building MEMELAND one meme at a time • 📧 9gag9gag.com • CEO ➡️ 9gagceo.</td>
<td style="text-align: left;">https://pbs.twimg.com/profile_images/1695636573294125056/Jj9IWW10_400x400.jpg</td>
<td style="text-align: right;">16812312</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">https://twitter.com/9GAG/status/1836888251941998992</td>
</tr>
<tr class="even">
<td style="text-align: right;">35</td>
<td style="text-align: left;">19.09.24 06:01</td>
<td style="text-align: left;">Me: <em>sends “Good morning” text</em> Also me: <em>sleeps again</em></td>
<td style="text-align: left;">https://pbs.twimg.com/media/GXz48AYXMAA4-Wm?format=jpg&amp;name=medium</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">475</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">9GAG ❤️ Memeland</td>
<td style="text-align: left;">9GAG</td>
<td style="text-align: left;">Building MEMELAND one meme at a time • 📧 9gag9gag.com • CEO ➡️ 9gagceo.</td>
<td style="text-align: left;">https://pbs.twimg.com/profile_images/1695636573294125056/Jj9IWW10_400x400.jpg</td>
<td style="text-align: right;">16812312</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">https://twitter.com/9GAG/status/1836616460271030578</td>
</tr>
<tr class="odd">
<td style="text-align: right;">36</td>
<td style="text-align: left;">09.10.24 01:00</td>
<td style="text-align: left;">Trade in. Upgrade. Save. It’s a win-win-win.</td>
<td style="text-align: left;">https://scontent-ham3-1.xx.fbcdn.net/v/t39.35426-6/462218991_2262824920752352_7170739144707876726_n.jpg?stp=dst-jpg_s600x600&amp;_nc_cat=105&amp;ccb=1-7&amp;_nc_sid=c53f8f&amp;_nc_ohc=8iy6cVBWpdsQ7kNvgG2iyBj&amp;_nc_ht=scontent-ham3-1.xx&amp;_nc_gid=Au5_Py3fxlUQdue1avtqNle&amp;oh=00_AYAy5jqXGlkDzj6L1-hJD-AJ_RXQKg_afDs2aZ1kBcV–g&amp;oe=670E8B8A</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">396</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">Apple</td>
<td style="text-align: left;">Apple</td>
<td style="text-align: left;">Apple.com</td>
<td style="text-align: left;">https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F8ed3d547-94ff-48e1-9f20-8c14a7030a02_2000x2000.jpeg</td>
<td style="text-align: right;">9712532</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">https://www.apple.com/shop/buy-mac/macbook-pro/16-inch?cid=wwa-us-soc-mac-macdt-socl-rbwfm-staf-infe-cpc-mos-mobtab-amact-gnt-broa-bnlp-lfnnl-usen-sngl-static-11ar-ban-macpro-trdn-rnge-buy-na-na-na-04807071</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">https://www.facebook.com/ads/library/?active_status=active&amp;ad_type=all&amp;country=DE&amp;id=513634761464978&amp;media_type=all&amp;search_type=page&amp;view_all_page_id=434174436675167</td>
</tr>
<tr class="even">
<td style="text-align: right;">37</td>
<td style="text-align: left;">10.10.24 01:00</td>
<td style="text-align: left;">Track your sleep, strain, stress, recovery, and more – on a high-powered device you’ll forget you’re even wearing.</td>
<td style="text-align: left;">https://scontent-ham3-1.xx.fbcdn.net/v/t39.35426-6/456453687_1497228568338575_3460451067821947560_n.jpg?stp=dst-jpg_s600x600&amp;_nc_cat=108&amp;ccb=1-7&amp;_nc_sid=c53f8f&amp;_nc_ohc=s0zq2rnJIbYQ7kNvgEA5dEc&amp;_nc_ht=scontent-ham3-1.xx&amp;_nc_gid=Ar8I66iuX4byWiPP-Wa2iZK&amp;oh=00_AYAcfU0N2dPWf9iX1J78Z0qw-uFC0KjQS7_Si_G21NRDmg&amp;oe=670EA829</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">203</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">41</td>
<td style="text-align: left;">WHOOP</td>
<td style="text-align: left;">WHOOP</td>
<td style="text-align: left;">Your wearable health &amp; fitness coach on a mission to unlock human performance. Join now and shop our latest styles 👇</td>
<td style="text-align: left;">https://cdn-1.webcatalog.io/catalog/whoop/whoop-icon-filled-256.png?v=1727793667542</td>
<td style="text-align: right;">98445</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">https://www.whoop.com/</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">https://www.facebook.com/ads/library/?active_status=active&amp;ad_type=all&amp;country=DE&amp;id=884008727118967&amp;media_type=all&amp;search_type=page&amp;view_all_page_id=314298918730028</td>
</tr>
<tr class="odd">
<td style="text-align: right;">38</td>
<td style="text-align: left;">11.10.24 01:00</td>
<td style="text-align: left;">Get powerful AI tools in a pocket-friendly package. Get the the all new Galaxy Z Flip6 and save up to $650 with trade-in.</td>
<td style="text-align: left;">https://scontent-ham3-1.xx.fbcdn.net/v/t39.35426-6/461785311_849420040637530_4189807201330104983_n.jpg?stp=dst-jpg_s600x600&amp;_nc_cat=109&amp;ccb=1-7&amp;_nc_sid=c53f8f&amp;_nc_ohc=_zSkXBev5O8Q7kNvgGd-3-L&amp;_nc_ht=scontent-ham3-1.xx&amp;_nc_gid=A6T__p18PiafwzhxKZvMoiE&amp;oh=00_AYCfhZS2xVPfuYEfNUttcHbnivX2017oazxDp4SLd_bEng&amp;oe=670E9DD7</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Samsung US</td>
<td style="text-align: left;">SamsungUS</td>
<td style="text-align: left;">Official Twitter of Samsung USA.</td>
<td style="text-align: left;">https://i.pinimg.com/originals/74/79/a0/7479a0a02cf333e01e13d1b6d08af800.jpg</td>
<td style="text-align: right;">75937</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">https://www.samsung.com/us/smartphones/galaxy-z-flip6/buy/galaxy-z-flip6-512gb-unlocked-sm-f741uakexaa/</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">https://www.facebook.com/ads/library/?active_status=active&amp;ad_type=all&amp;country=DE&amp;id=800744292023909&amp;media_type=all&amp;search_type=page&amp;view_all_page_id=7224956785</td>
</tr>
<tr class="even">
<td style="text-align: right;">39</td>
<td style="text-align: left;">12.10.24 01:00</td>
<td style="text-align: left;">Bring home the Nintendo Switch™ system and get everyone in on the fun together!</td>
<td style="text-align: left;">https://scontent-ham3-1.xx.fbcdn.net/v/t39.35426-6/461833323_1598276837567833_385467090264512800_n.jpg?stp=dst-jpg_s600x600&amp;_nc_cat=108&amp;ccb=1-7&amp;_nc_sid=c53f8f&amp;_nc_ohc=Yld5Mu9Ls54Q7kNvgGlM207&amp;_nc_ht=scontent-ham3-1.xx&amp;_nc_gid=AGzr0CP_zIG-20aQne5-Az6&amp;oh=00_AYDry9MlNds6mS_mzOBiFatTpHy9qdqDPTMda84KJy3Gjw&amp;oe=670E8CA6</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">9339</td>
<td style="text-align: right;">1903</td>
<td style="text-align: right;">240</td>
<td style="text-align: left;">Nintendo of America</td>
<td style="text-align: left;">NintendoAmerica</td>
<td style="text-align: left;">Welcome to the official Nintendo profile for gaming news! We’re listening, too. For ESRB ratings go to http://esrb.org</td>
<td style="text-align: left;">https://pbs.twimg.com/profile_images/1539293929031421958/cy-uzR2t_400x400.jpg</td>
<td style="text-align: right;">13948183</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">https://www.nintendo.com/us/store/products/nintendo-switch-lite-gray/</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">https://www.facebook.com/ads/library/?active_status=active&amp;ad_type=all&amp;country=DE&amp;id=1053573702629422&amp;media_type=all&amp;search_type=page&amp;view_all_page_id=1125429570886433</td>
</tr>
<tr class="odd">
<td style="text-align: right;">40</td>
<td style="text-align: left;">13.10.24 01:00</td>
<td style="text-align: left;">Legendary noise cancellation now comes in a bold new shade. Shop Bose QuietComfort Headphones in limited-edition Sandstone.</td>
<td style="text-align: left;">https://scontent-ham3-1.xx.fbcdn.net/v/t39.35426-6/449312743_2744495332380149_827947157860749378_n.jpg?stp=dst-jpg_s600x600&amp;_nc_cat=102&amp;ccb=1-7&amp;_nc_sid=c53f8f&amp;<em>nc_ohc=RZ2kDljucacQ7kNvgE-0db</em>&amp;_nc_ht=scontent-ham3-1.xx&amp;_nc_gid=AVwJcHYfDMnOHYjQepUXZCO&amp;oh=00_AYAFyDp3EHj3Gk_H1z_ApTeyOJuRPDKNMZ6XvR4slUC5qw&amp;oe=670EB46D</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">11039</td>
<td style="text-align: right;">6099</td>
<td style="text-align: right;">230</td>
<td style="text-align: left;">Bose</td>
<td style="text-align: left;">Bose</td>
<td style="text-align: left;">Sound Is Power. For support, follow BoseService.</td>
<td style="text-align: left;">https://logodownload.org/wp-content/uploads/2019/07/bose-logo-3.png</td>
<td style="text-align: right;">2339194</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">https://www.bose.com/p/noise-cancelling-headphones/quietcomfort-acoustic-noise-cancelling-headphones/QC-HEADPHONEARN.html</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">https://www.facebook.com/ads/library/?id=471047825791376</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="data" class="level3" data-number="1.1.4">
<h3 data-number="1.1.4" class="anchored" data-anchor-id="data"><span class="header-section-number">1.1.4</span> Data</h3>
<section id="final-sample" class="level4" data-number="1.1.4.1">
<h4 data-number="1.1.4.1" class="anchored" data-anchor-id="final-sample"><span class="header-section-number">1.1.4.1</span> Final Sample</h4>
<p>Our dataset comprises 300 participants and 10,377 observations at the participant <span class="math inline">\(\times\)</span> post level. In our analyses, we only focus on sponsored posts which is why our final sample comprises 1,283 observations on the participant <span class="math inline">\(\times\)</span> <em>sponsored</em> post level. This is less than the expected five observations per participant due to two reasons. First, due to connectivity issues: no dwell time data were recorded for around 3.67% of individual–sponsored post pairs. Second, we excluded the first and last two posts of each feed (i.e., <span class="math inline">\(300 \times 4\)</span> observations) from our analysis, as meaningful dwell times couldn’t be determined for these. This is because participants were familiarizing themselves with the interface at the start and deciding whether to proceed to the next stage of the study at the end of the feeds.</p>
</section>
<section id="variables" class="level4" data-number="1.1.4.2">
<h4 data-number="1.1.4.2" class="anchored" data-anchor-id="variables"><span class="header-section-number">1.1.4.2</span> Variables</h4>
<p>We present summary statistics for our final sample, both for participant-level observations and self-reports as well as for user interaction data at the participant <span class="math inline">\(\times\)</span> sponsored post level (see <a href="#tbl-summary-participant-level">Table&nbsp;<span>1.2</span></a> and <a href="#tbl-summary-post-participant-level">Table&nbsp;<span>1.3</span></a>, respectively). [Merge the tables and create sub-headings or panels.]</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-summary-participant-level" class="anchored">

<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Table&nbsp;1.2:  Summary Statistics on the Participant-Level </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Statistic </th>
   <th style="text-align:right;"> N </th>
   <th style="text-align:right;"> Mean </th>
   <th style="text-align:right;"> St. Dev. </th>
   <th style="text-align:right;"> Min </th>
   <th style="text-align:right;"> Max </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Age </td>
   <td style="text-align:right;"> 300 </td>
   <td style="text-align:right;"> 29.42 </td>
   <td style="text-align:right;"> 4.54 </td>
   <td style="text-align:right;"> 18 </td>
   <td style="text-align:right;"> 49 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Female </td>
   <td style="text-align:right;"> 300 </td>
   <td style="text-align:right;"> 0.53 </td>
   <td style="text-align:right;"> 0.50 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Desktop </td>
   <td style="text-align:right;"> 300 </td>
   <td style="text-align:right;"> 0.72 </td>
   <td style="text-align:right;"> 0.45 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Recall Apple </td>
   <td style="text-align:right;"> 300 </td>
   <td style="text-align:right;"> 0.34 </td>
   <td style="text-align:right;"> 0.47 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> .. Bose </td>
   <td style="text-align:right;"> 300 </td>
   <td style="text-align:right;"> 0.31 </td>
   <td style="text-align:right;"> 0.46 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> .. Nintendo </td>
   <td style="text-align:right;"> 300 </td>
   <td style="text-align:right;"> 0.48 </td>
   <td style="text-align:right;"> 0.50 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> .. Samsung </td>
   <td style="text-align:right;"> 300 </td>
   <td style="text-align:right;"> 0.27 </td>
   <td style="text-align:right;"> 0.45 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> .. Whoop </td>
   <td style="text-align:right;"> 300 </td>
   <td style="text-align:right;"> 0.10 </td>
   <td style="text-align:right;"> 0.30 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-summary-post-participant-level" class="anchored">

<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Table&nbsp;1.3:  Summary Statistics on the Sponsored Post x Participant-Level </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Statistic </th>
   <th style="text-align:right;"> N </th>
   <th style="text-align:right;"> Mean </th>
   <th style="text-align:right;"> St. Dev. </th>
   <th style="text-align:right;"> Min </th>
   <th style="text-align:right;"> Max </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Position in Feed </td>
   <td style="text-align:right;"> 1283 </td>
   <td style="text-align:right;"> 20.577 </td>
   <td style="text-align:right;"> 10.371 </td>
   <td style="text-align:right;"> 3.000 </td>
   <td style="text-align:right;"> 38.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Likes </td>
   <td style="text-align:right;"> 1283 </td>
   <td style="text-align:right;"> 0.035 </td>
   <td style="text-align:right;"> 0.184 </td>
   <td style="text-align:right;"> 0.000 </td>
   <td style="text-align:right;"> 1.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Replies </td>
   <td style="text-align:right;"> 1283 </td>
   <td style="text-align:right;"> 0.003 </td>
   <td style="text-align:right;"> 0.056 </td>
   <td style="text-align:right;"> 0.000 </td>
   <td style="text-align:right;"> 1.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Seconds in Viewport </td>
   <td style="text-align:right;"> 1283 </td>
   <td style="text-align:right;"> 3.923 </td>
   <td style="text-align:right;"> 7.198 </td>
   <td style="text-align:right;"> 0.015 </td>
   <td style="text-align:right;"> 129.107 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> log(Seconds in Viewport) </td>
   <td style="text-align:right;"> 1283 </td>
   <td style="text-align:right;"> 0.560 </td>
   <td style="text-align:right;"> 1.395 </td>
   <td style="text-align:right;"> -4.200 </td>
   <td style="text-align:right;"> 4.861 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Post Height </td>
   <td style="text-align:right;"> 1283 </td>
   <td style="text-align:right;"> 525.118 </td>
   <td style="text-align:right;"> 163.048 </td>
   <td style="text-align:right;"> 147.000 </td>
   <td style="text-align:right;"> 753.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Dwell Time </td>
   <td style="text-align:right;"> 1283 </td>
   <td style="text-align:right;"> 0.002 </td>
   <td style="text-align:right;"> 0.004 </td>
   <td style="text-align:right;"> -0.027 </td>
   <td style="text-align:right;"> 0.025 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<section id="position-in-feed" class="level5" data-number="1.1.4.2.1">
<h5 data-number="1.1.4.2.1" class="anchored" data-anchor-id="position-in-feed"><span class="header-section-number">1.1.4.2.1</span> Position in Feed</h5>
<p>Position in Feed describes our independent variable. Because we randomized the order in which the content appeared (i.e., Position in Feed acts as a within-subject factor) and because we excluded observations positioned at the beginning and the end of the feed, we observe a sample mean of 20.58 as well as a minimum and maximum of 3 and 38, respectively. As, we randomly manipulated the position in which each post was displayed exogenously between subjects, each sequence in which participants browsed through ads was unique.</p>
<div class="cell" data-fig-cap-location="top">
<div class="cell-output-display">
<div id="fig-brand-order" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="cases_files/figure-html/fig-brand-order-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1.2: Distribution of Sponsored Post Impressions by Position in Feed and Brand across All Participants</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-brand-order">Figure&nbsp;<span>1.2</span></a>, each line represents the number of times a sponsored post for a specific brand appeared at each position across all participants. As the placements were fully randomized, we observed some random variability that naturally fluctuates around the expected value of 7.5 impressions per position (as indicated by dashed lines).<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Taken together, this suggests that randomization within the DICE app was effective.</p>
</section>
<section id="visibility-measures" class="level5" data-number="1.1.4.2.2">
<h5 data-number="1.1.4.2.2" class="anchored" data-anchor-id="visibility-measures"><span class="header-section-number">1.1.4.2.2</span> Visibility Measures</h5>
<p>The variable Seconds in Viewport we report in <a href="#tbl-summary-post-participant-level">Table&nbsp;<span>1.3</span></a> describes the number of seconds in which at least 50 percent of a post’s pixels were visible on screen (sample mean is 3.92 seconds), which we log-transform to reduce skewness. To calculate our Dwell Time measure we use throughout the analyses in this case study, we then divide it by Post Height, that is, the height in which the corresponding sponsored post was displayed on a participant’s screen as this variable varies within participants and between sponsored posts. The resulting Dwell Time has a sample mean of 0.002 with a Fisher-Pearson skewness of 0.38, which is considered as approximately symmetric <span class="citation" data-cites="Bulmer_1979">(<a href="references.html#ref-Bulmer_1979" role="doc-biblioref">Bulmer 1979</a>)</span>.</p>
</section>
<section id="reactions" class="level5" data-number="1.1.4.2.3">
<h5 data-number="1.1.4.2.3" class="anchored" data-anchor-id="reactions"><span class="header-section-number">1.1.4.2.3</span> Reactions</h5>
<p>We measured reactions such as likes and replies to individual posts. In the full sample (which includes organic posts), we observe 144 (30) participants who liked (replied to) any post in the feed. Considering sponsored posts only, however, we only count 32 (4) participants who liked (replied to) at least one post, which is why we do not consider these explicit engagement metrics in our analyses.</p>
</section>
<section id="recall" class="level5" data-number="1.1.4.2.4">
<h5 data-number="1.1.4.2.4" class="anchored" data-anchor-id="recall"><span class="header-section-number">1.1.4.2.4</span> Recall</h5>
<div class="cell">

</div>
<p><a href="#tbl-summary-participant-level">Table&nbsp;<span>1.2</span></a> shows that recall varied by brand. Between 48.00% (Nintendo) and 10.33% (Whoop) recalled seeing the sponsored post. Only 35 participants indicated that they did not remember seeing any sponsored post.</p>
<p><a href="#tbl-show-data-1">Table&nbsp;<span>1.4</span></a> shows an excerpt of the processed data to illustrate its nested (i.e., “long”) structure.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-show-data-1" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;1.4: Processed Data Analyzed in Study 1</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 3%">
<col style="width: 6%">
<col style="width: 2%">
<col style="width: 7%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Participant ID</th>
<th style="text-align: right;">Post ID</th>
<th style="text-align: left;">Sponsored Post</th>
<th style="text-align: left;">Brand</th>
<th style="text-align: right;">Position in Feed</th>
<th style="text-align: left;">Likes</th>
<th style="text-align: left;">Replies</th>
<th style="text-align: right;">Seconds in Viewport</th>
<th style="text-align: right;">log(Seconds in Viewport)</th>
<th style="text-align: right;">Post Height</th>
<th style="text-align: right;">Dwell Time</th>
<th style="text-align: right;">Age</th>
<th style="text-align: left;">Female</th>
<th style="text-align: left;">Desktop</th>
<th style="text-align: left;">Recall Apple</th>
<th style="text-align: left;">Recall Bose</th>
<th style="text-align: left;">Recall Nintendo</th>
<th style="text-align: left;">Recall Samsung</th>
<th style="text-align: left;">Recall Whoop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">66ee9436fdc916ec83068569</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">35</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: right;">-2.4889147</td>
<td style="text-align: right;">383</td>
<td style="text-align: right;">-0.0064985</td>
<td style="text-align: right;">33</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">66ee9436fdc916ec83068569</td>
<td style="text-align: right;">13</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">36</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.117</td>
<td style="text-align: right;">-2.1455813</td>
<td style="text-align: right;">420</td>
<td style="text-align: right;">-0.0051085</td>
<td style="text-align: right;">33</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">66ee9436fdc916ec83068569</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">37</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.150</td>
<td style="text-align: right;">-1.8971200</td>
<td style="text-align: right;">416</td>
<td style="text-align: right;">-0.0045604</td>
<td style="text-align: right;">33</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">66ee9436fdc916ec83068569</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">38</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.167</td>
<td style="text-align: right;">-1.7897615</td>
<td style="text-align: right;">402</td>
<td style="text-align: right;">-0.0044521</td>
<td style="text-align: right;">33</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">66ee9436fdc916ec83068569</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">39</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.234</td>
<td style="text-align: right;">-1.4524342</td>
<td style="text-align: right;">388</td>
<td style="text-align: right;">-0.0037434</td>
<td style="text-align: right;">33</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">66ee9436fdc916ec83068569</td>
<td style="text-align: right;">34</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">40</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2.705</td>
<td style="text-align: right;">0.9951019</td>
<td style="text-align: right;">385</td>
<td style="text-align: right;">0.0025847</td>
<td style="text-align: right;">33</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">66f043f0c38f7c2ec60770e4</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">4.614</td>
<td style="text-align: right;">1.5290952</td>
<td style="text-align: right;">622</td>
<td style="text-align: right;">0.0024584</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">66f043f0c38f7c2ec60770e4</td>
<td style="text-align: right;">24</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.376</td>
<td style="text-align: right;">-0.9781661</td>
<td style="text-align: right;">507</td>
<td style="text-align: right;">-0.0019293</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">66f043f0c38f7c2ec60770e4</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">1.042</td>
<td style="text-align: right;">0.0411419</td>
<td style="text-align: right;">512</td>
<td style="text-align: right;">0.0000804</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">66f043f0c38f7c2ec60770e4</td>
<td style="text-align: right;">36</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Apple</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.180</td>
<td style="text-align: right;">-1.7147984</td>
<td style="text-align: right;">622</td>
<td style="text-align: right;">-0.0027569</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">66f043f0c38f7c2ec60770e4</td>
<td style="text-align: right;">37</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Whoop</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.382</td>
<td style="text-align: right;">-0.9623347</td>
<td style="text-align: right;">646</td>
<td style="text-align: right;">-0.0014897</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="analysis" class="level3" data-number="1.1.5">
<h3 data-number="1.1.5" class="anchored" data-anchor-id="analysis"><span class="header-section-number">1.1.5</span> Analysis</h3>
<p>To estimate the impact of ad positioning on brand recall in social media feeds, we employed a mixed-effects logistic regression model with brand fixed effects to account for the binary nature of recall outcome (recalled vs.&nbsp;not recalled) while considering the hierarchical structure of our data: multiple observations nested within participants and ads. The model can be expressed as:</p>
<p><span class="math display">\[
\log\left(\frac{p_{ij}}{1-p_{ij}}\right) = a + \mathbf{x}_{ij} \mathbf{b} + \sum_{k=1}^{K-1} \gamma_k Brand_k + u_i + \epsilon_{ij}
\]</span></p>
<p>where <span class="math inline">\(p_{ij}\)</span> is the probability of brand recall for the <span class="math inline">\(i\)</span>-th participant and <span class="math inline">\(j\)</span>-th observation, <span class="math inline">\(a\)</span> is the intercept, <span class="math inline">\(\mathbf{x}_{ij}\)</span> is a vector of continuous predictors (position in feed and dwell time) with corresponding coefficient vector <span class="math inline">\(\mathbf{b}\)</span>. The term <span class="math inline">\(\gamma_k\)</span> represents the fixed effects for each brand <span class="math inline">\(k\)</span> (with one Apple serving as the reference category), and <span class="math inline">\(u_i\)</span> captures the fixed effects for each participant. Finally, <span class="math inline">\(\epsilon{ij}\)</span> represents the idiosyncratic error term for participant <span class="math inline">\(i\)</span> and observation <span class="math inline">\(j\)</span>.</p>
<p>The random participant effects <span class="math inline">\(u_i\)</span> are justified by the experimental design, as the random assignment of ad positions ensures zero correlation between participant characteristics and the explanatory variables. Brand effects are treated as fixed parameters rather than random effects, allowing for potential correlation between brand characteristics and key explanatory variables such as dwell time.</p>
</section>
</section>
<section id="sec-brand-safety-case" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="sec-brand-safety-case"><span class="header-section-number">1.2</span> Case Study 2: When Does Context Harm Brands? Manipulating Feed Composition to Study Brand Safety</h2>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<p>The primary goal of our second case study is to demonstrate another feature of the DICE app: the experimental manipulation of (advertising) context. Whereas Case Study 1 used a single set of social media posts and randomized its display sequence, this study creates different sets of content for different groups of participants while keeping one sponsored post constant across all groups. Accordingly, we systematically manipulate the context in which participants encounter the sponsored post by varying the surrounding content they see.</p>
<p>We demonstrate this capability by examining brand safety in social media advertising. Brand safety refers to strategies and measures dedicated to ensuring that advertising does not appear in contexts that could harm brand reputation <span class="citation" data-cites="FournierSrinivasan_2023 Porter_2021">(<a href="references.html#ref-FournierSrinivasan_2023" role="doc-biblioref">Fournier and Srinivasan 2023</a>; <a href="references.html#ref-Porter_2021" role="doc-biblioref">Porter 2021</a>)</span>. This concern is particularly relevant for social media advertising, where platforms use automated systems to place ads in dynamic, user-generated content environments because, these systems often lack the nuanced understanding needed to identify potentially problematic contexts. Industry reports suggest that 75% of brands have experienced brand-unsafe exposures <span class="citation" data-cites="GumGum_2017">(<a href="references.html#ref-GumGum_2017" role="doc-biblioref">GumGum Inc. 2017</a>)</span>, with ads frequently appearing alongside problematic content despite blacklists and negative targeting strategies <span class="citation" data-cites="SimonovVallettiVeiga_2024 AhmadEtAl_2024">(<a href="references.html#ref-SimonovVallettiVeiga_2024" role="doc-biblioref">Simonov, Valletti, and Veiga 2024</a>; <a href="references.html#ref-AhmadEtAl_2024" role="doc-biblioref">Ahmad et al. 2024</a>)</span>. Not solely by <em>controlling</em> but by <em>manipulating</em> the sponsored post’s context (i.e., organic posts), the DICE app allows us to investigate sensitive challenges in an experimental setting without risking actual brand reputation damage (which would make field settings infeasible).</p>
<section id="experimental-design-1" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="experimental-design-1"><span class="header-section-number">1.2.1</span> Experimental Design</h3>
<p>To examine how brand-(un)safe contexts affect brand perceptions, we created two social media feeds that were identical in structure but varied in their content surrounding a sponsored post. Both feeds contained the same number of organic posts and one identical sponsored post, with the only difference being the thematic focus of the organic content.</p>
<p>To ensure ecological validity, we populated our experimental feeds with actual tweets covering Brazil: one feed featured coverage of severe flooding that claimed at least 95 lives <span class="citation" data-cites="Buschschlueter_2024">(<a href="references.html#ref-Buschschlueter_2024" role="doc-biblioref">Buschschlüter 2024</a>)</span>, while the other contained typical Brazil-related content including Madonna’s free concert in Rio de Janeiro, soccer matches, and travel experiences. This approach mirrors real-world scenarios where automated ad placement systems, operating primarily on keywords (e.g., “Brazil”), might place the same ad in vastly different contextual environments.</p>
<p>The sponsored post, a fictitious KLM advertisement promoting flights to Brazil, was identical across both conditions. The creative featured the tagline: <em>“Brazil’s wild beauty calls! Experience nature like never before. Book your breathtaking adventure with KLM.”</em> This messaging, while typically appropriate for airline promotion, becomes strikingly insensitive when juxtaposed against a feed focusing on the natural disaster in the region advertised, which is precisely the type of contextual mismatch that automated systems might create.</p>
<p>To control for position effects identified in Case Study 1, we placed KLM’s sponsored post in fifth position in both conditions. While this position remained constant, we randomized the sequence of organic posts between subjects to ensure any effects weren’t driven by specific content adjacencies.</p>
</section>
<section id="procedure-1" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="procedure-1"><span class="header-section-number">1.2.2</span> Procedure</h3>
<div class="cell">

</div>
<div class="cell">

</div>
<p>As in the first case study, participants browsed the simulated feed on their own devices (75% Desktop, 21% Mobile, and 4% Tablet). After scrolling through the feed, we redirected participants to a Qualtrics survey in which they first provided demographic information as a filler task. Subsequently, we measured whether participants recalled seeing the ads by the five brands in the feed. Specifically, we measured cued recall for which we showed participants a list of ten brands and asked them to indicate indicate which ones they remembered seeing. We also included a no-recall option to reduce false positives. To assess brand perceptions, participants then evaluated their attitudes toward KLM using three seven-point scales (1 = “Negative/Unfavorable/Dislike” and 7 = “Positive/Favorable/Like”; <span class="math inline">\(\alpha\)</span> = 0.96). Subsequently, participants indicated their awareness of the Brazil flooding situation before reading a debriefing and being redirected to Prolific.</p>
</section>
<section id="stimuli-1" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="stimuli-1"><span class="header-section-number">1.2.3</span> Stimuli</h3>
<p>Building on the CSV file structure introduced in Case Study 1, we created a file containing two distinct sets of content: nineteen organic posts for each experimental condition, plus one sponsored post that needed to appear in both feeds. To ensure the sponsored post would appear in both conditions while maintaining DICE’s CSV structure, we entered the sponsored post twice in the file - once for each condition. This resulted in a file with forty rows total: nineteen organic posts for each condition plus the sponsored post appearing twice. Each post’s content was specified in columns such as <code>&lt;text&gt;</code> and <code>&lt;username&gt;</code>. We used the <code>&lt;condition&gt;</code> parameter to distinguish between our “appropriate” (brand-safe) and “inappropriate” (brand-unsafe) feeds, assigning each row (i.e., each post) to its respective condition. Similar to Case Study 1, we left the <code>&lt;sequence&gt;</code> column empty for organic posts to enable randomization, with one key exception: the KLM sponsored post was assigned a fixed <code>&lt;sequence&gt;</code> value of “5” to ensure consistent positioning across conditions. We marked this post as sponsored using the <code>&lt;sponsored&gt;</code> parameter and included a KLM landing page URL in the <code>&lt;target&gt;</code> column for participants who clicked on the ad. The resulting CSV file was uploaded to an online repository to generate a URL for the DICE app.</p>
<p><a href="#tbl-stimuli-case-2">Table&nbsp;<span>1.5</span></a> shows an excerpt of the exact CSV files we used to create the stimuli for this study. You can download that file <a href="https://raw.githubusercontent.com/Howquez/DICE/refs/heads/main/studies/brand_safety/stimuli/brazil.csv" target="_blank">here</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-stimuli-case-2" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;1.5: CSV File Used in Study 2</caption>
<colgroup>
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 29%">
<col style="width: 17%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 18%">
<col style="width: 7%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 5%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">doc_id</th>
<th style="text-align: left;">datetime</th>
<th style="text-align: left;">text</th>
<th style="text-align: left;">media</th>
<th style="text-align: left;">alt_text</th>
<th style="text-align: right;">likes</th>
<th style="text-align: right;">reposts</th>
<th style="text-align: right;">replies</th>
<th style="text-align: left;">username</th>
<th style="text-align: left;">handle</th>
<th style="text-align: left;">user_description</th>
<th style="text-align: left;">user_image</th>
<th style="text-align: right;">user_followers</th>
<th style="text-align: right;">sponsored</th>
<th style="text-align: left;">target</th>
<th style="text-align: left;">condition</th>
<th style="text-align: right;">sequence</th>
<th style="text-align: right;">commented_post</th>
<th style="text-align: left;">source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">08.05.24 09:30</td>
<td style="text-align: left;">Brazil’s wild beauty calls! Experience nature like never before. Book your breathtaking adventure with KLM.</td>
<td style="text-align: left;">https://i.postimg.cc/MGQtKsh2/brazil-wild-beauty.webp</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">336</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">KLM</td>
<td style="text-align: left;">KLM</td>
<td style="text-align: left;">Official global account of KLM. FAQ about flying from AMS: http://klmf.ly/Schiphol. To learn how we can assist you, please check: http://klmf.ly/ContactCentre.</td>
<td style="text-align: left;">https://pbs.twimg.com/profile_images/1807736403385561088/HaxXwA-t_400x400.jpg</td>
<td style="text-align: right;">2223756</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">https://www.klm.com.br/en-br/flights-from-brazil</td>
<td style="text-align: left;">appropriate</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: left;">08.05.24 09:30</td>
<td style="text-align: left;">Madonna shines in a custom Jean Paul Gaultier Haute Couture once again as she took the stage for her legendary grand finale for her ‘Celebration Tour’ in Brazil 💚</td>
<td style="text-align: left;">https://pbs.twimg.com/media/GM5QxcZXMAA4nDR?format=jpg&amp;name=large</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">17123</td>
<td style="text-align: right;">2123</td>
<td style="text-align: right;">117</td>
<td style="text-align: left;">JPGaultier</td>
<td style="text-align: left;">Jean Paul Gaultier</td>
<td style="text-align: left;">Jean Paul Gaultier</td>
<td style="text-align: left;">https://pbs.twimg.com/profile_images/1780899814722473984/u02Lhtw4_400x400.jpg</td>
<td style="text-align: right;">1423123</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">appropriate</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">https://twitter.com/JPGaultier/status/1787455029789499619</td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: left;">08.05.24 09:30</td>
<td style="text-align: left;">Waved Woodpecker (Celeus undatus) in Brazil 🐦🇧🇷 📷 Schuler Franz ©️ #Brazil #nature #wildlife #photography</td>
<td style="text-align: left;">https://pbs.twimg.com/media/GHOD_EjXkAACxmS?format=jpg&amp;name=medium</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">1109</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">Liberta Cherguia 🇪🇺</td>
<td style="text-align: left;">MbarkCherguia</td>
<td style="text-align: left;">🌳 Nature lover | 📸 Capturing nature’s beauty | Open to collaborations | Follow for stunning landscapes! 🌄 | Check out Geniustechw for art, tech &amp; culture</td>
<td style="text-align: left;">https://pbs.twimg.com/profile_images/1748768033231798272/yx0DbMM4_400x400.jpg</td>
<td style="text-align: right;">23249</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">appropriate</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">https://twitter.com/MbarkCherguia/status/1761897016681017449</td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: left;">08.05.24 09:30</td>
<td style="text-align: left;">Using sustainable materials and innovative folding doors, Casa Sui promises an interactive living space. Through its nature-inspired design, it perfectly blends with its surroundings. Details: https://arc.ht/3S1LWWX | 📍 Belo Horizonte, Brazil #ProjectOfTheDay #ArchitizerAwards</td>
<td style="text-align: left;">https://pbs.twimg.com/media/GEChwN4XQAA17mq?format=jpg&amp;name=medium</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">311</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Architizer</td>
<td style="text-align: left;">Architizer</td>
<td style="text-align: left;">Architizer is the home of architectural inspiration.</td>
<td style="text-align: left;">https://pbs.twimg.com/profile_images/842415551955759109/om8egmBt_400x400.jpg</td>
<td style="text-align: right;">1203859</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">appropriate</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">https://twitter.com/Architizer/status/1747574513343025652</td>
</tr>
<tr class="odd">
<td style="text-align: right;">19</td>
<td style="text-align: left;">08.05.24 09:30</td>
<td style="text-align: left;">The flora in Pará, Brazil, is essential for its economy, but preserving #biodiversity is equally important. Integrating it into value chains benefits the climate, people, and the economy. Learn more with this nature_org infographic!</td>
<td style="text-align: left;">https://pbs.twimg.com/media/GAvWidjb0AAMYMU?format=jpg&amp;name=4096x4096</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">UN Biodiversity</td>
<td style="text-align: left;">UN Biodiversity</td>
<td style="text-align: left;">Official account of the Secretariat of the Convention on Biological Diversity. Our Acting Executive Secretary hdavidcooper</td>
<td style="text-align: left;">https://pbs.twimg.com/profile_images/1737083733147070464/irgdpyhW_400x400.jpg</td>
<td style="text-align: right;">203847</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">appropriate</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">https://twitter.com/UNBiodiversity/status/1735162703465890034</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: left;">08.05.24 09:30</td>
<td style="text-align: left;">Brazil overlaid onto Europe</td>
<td style="text-align: left;">https://pbs.twimg.com/media/GNCfMeJXUAAn61W?format=jpg&amp;name=large</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2899</td>
<td style="text-align: right;">333</td>
<td style="text-align: right;">37</td>
<td style="text-align: left;">Epic Maps 🗺️</td>
<td style="text-align: left;">Locati0ns</td>
<td style="text-align: left;">Educational and informative world Maps 🗺️. Scroll Down &amp; Get More Knowledge. We do not own any content posted. Dm for removal/credit.</td>
<td style="text-align: left;">https://pbs.twimg.com/profile_images/1369972073758564355/nzPns41x_400x400.jpg</td>
<td style="text-align: right;">850949</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">appropriate</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">https://twitter.com/Locati0ns/status/1788104092574998635</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: left;">08.05.24 09:30</td>
<td style="text-align: left;">I don’t say this lightly - but the floods in Porto Alegre, Brazil, are looking comparable to what Katrina did to New Orleans in 2005 – massive evacuations, water &amp; power outages, key infrastructure damaged, parts of city unlivable, possible long-term consequences</td>
<td style="text-align: left;">https://pbs.twimg.com/media/GNC-y3PWoAAGfil?format=jpg&amp;name=900x900</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">3020</td>
<td style="text-align: right;">550</td>
<td style="text-align: right;">24</td>
<td style="text-align: left;">Brian Winter</td>
<td style="text-align: left;">BrazilBrian</td>
<td style="text-align: left;">Editor-in-chief AmerQuarterly. Latin American politics &amp; barbecue. ““O mais brasileiro dos texanos.”” Opinions mine.</td>
<td style="text-align: left;">https://pbs.twimg.com/profile_images/1696273071898800128/Qc439vin_400x400.jpg</td>
<td style="text-align: right;">71129</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">inappropriate</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">https://twitter.com/BrazilBrian/status/1788140902067634491</td>
</tr>
<tr class="even">
<td style="text-align: right;">22</td>
<td style="text-align: left;">08.05.24 09:30</td>
<td style="text-align: left;">Sentinel-2 satellite imagery from earlier today shows the incredible extent of the historic flooding in Rio Grande do Sul, Brazil. Just terrible.</td>
<td style="text-align: left;">https://saltwire.imgix.net/2024/5/7/brazil-floods-death-toll-rises-to-90-dozens-still-stranded.jpg?cs=srgb&amp;fit=crop&amp;h=568&amp;w=847&amp;dpr=2&amp;auto=enhance%2Cformat%2Ccompress</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">11239</td>
<td style="text-align: right;">34120</td>
<td style="text-align: right;">56</td>
<td style="text-align: left;">Nahel Belgherze</td>
<td style="text-align: left;">WxNB_</td>
<td style="text-align: left;">Covering extreme weather events around the world. Also interested in climate dynamics, geohazards &amp; satellite remote sensing. Views are my own.</td>
<td style="text-align: left;">https://pbs.twimg.com/profile_images/1729266199496736768/ADI5Spzl_400x400.jpg</td>
<td style="text-align: right;">51737</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">inappropriate</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">https://twitter.com/WxNB_/status/1787616302737035457</td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: left;">08.05.24 09:30</td>
<td style="text-align: left;">The sheer scale of the flooding in the metropolitan area of Porto Alegre, Brazil, which is home to over 4 million people, is hard to comprehend. Thousands of homes flooded, towns cut off, dozens killed, hundreds missing.</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2231</td>
<td style="text-align: right;">1415</td>
<td style="text-align: right;">51</td>
<td style="text-align: left;">Nahel Belgherze</td>
<td style="text-align: left;">WxNB_</td>
<td style="text-align: left;">Covering extreme weather events around the world. Also interested in climate dynamics, geohazards &amp; satellite remote sensing. Views are my own.</td>
<td style="text-align: left;">https://pbs.twimg.com/profile_images/1729266199496736768/ADI5Spzl_400x400.jpg</td>
<td style="text-align: right;">51737</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">inappropriate</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">https://twitter.com/WxNB_/status/1787942289349783798</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">

</div>
</section>
<section id="participants-and-randomization-checks" class="level3" data-number="1.2.4">
<h3 data-number="1.2.4" class="anchored" data-anchor-id="participants-and-randomization-checks"><span class="header-section-number">1.2.4</span> Participants and Randomization Checks</h3>
<p>We recruited 982 US-American participants (<span class="math inline">\(M_{age} = 39\)</span> years; 56% female) from Prolific. Participants were randomly assigned to view either the brand-safe feed (featuring general Brazil-related content) or the brand-unsafe feed (featuring flood coverage). A key advantage of DICE over observational and platform studies is its ability to implement true random assignment, allowing us to isolate the effect of context while canceling out other factors that might influence brand perception. To validate DICE’s randomization functionality, we examined the balance between treatment groups: as illustrated in <a href="#tbl-balance">Table&nbsp;<span>1.6</span></a>, the two treatment groups do not exhibit differences in observables. Following <span class="citation" data-cites="KerwinRostomSterck_2024">Kerwin, Rostom, and Sterck (<a href="references.html#ref-KerwinRostomSterck_2024" role="doc-biblioref">2024</a>)</span>, we also found support for balanced conditions in an omnibus test of joint orthogonality with randomization inference (<span class="math inline">\(p=\)</span> 0.42).</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-balance" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;1.6: Covariate Balance Across Conditions</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Covariate</th>
<th style="text-align: right;">Appropriate</th>
<th style="text-align: right;">Inappropriate</th>
<th style="text-align: right;">Difference</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean Age (Years)</td>
<td style="text-align: right;">38.689</td>
<td style="text-align: right;">38.609</td>
<td style="text-align: right;">-0.081</td>
<td style="text-align: right;">0.924</td>
</tr>
<tr class="even">
<td style="text-align: left;">Female (Percent)</td>
<td style="text-align: right;">57.669</td>
<td style="text-align: right;">53.550</td>
<td style="text-align: right;">-4.119</td>
<td style="text-align: right;">0.194</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="data-1" class="level3" data-number="1.2.5">
<h3 data-number="1.2.5" class="anchored" data-anchor-id="data-1"><span class="header-section-number">1.2.5</span> Data</h3>
<p>Our dataset comprises 982 participants and 15,343 observations at the participant <span class="math inline">\(\times\)</span> post level. Whereas Case Study 1 analyzed multiple sponsored posts across participants, here we focus on a single sponsored post (i.e., the KLM ad) viewed by all participants, which simplifies our analytical approach. Our final sample comprises 955 observations on the participant level, which is slightly less than the expected one observation per participant due to connectivity issues: no dwell time data were recorded for around 2.75% of the sponsored posts.</p>
<p>This simplified “short” data structure has two convenient methodological implications. First, because we analyze one observation per participant rather than nested data, we can apply simpler methods such as ordinary least squares (OLS) regressions in our analyses. Second, because we only focus on one sponsored post, we do not need to divide our dwell time measure by the post’s height as we did in Case Study 1. Both aspects increase the interpretability of our results.</p>
<p><a href="#tbl-show-data-2">Table&nbsp;<span>1.7</span></a> shows an excerpt of the processed data to illustrate its nested (i.e., “long”) structure.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-show-data-2" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;1.7: Processed Data Analyzed in Study 2</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 15%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Participant ID</th>
<th style="text-align: right;">Position in Feed</th>
<th style="text-align: left;">Likes</th>
<th style="text-align: left;">Replies</th>
<th style="text-align: right;">Seconds in Viewport</th>
<th style="text-align: right;">Dwell Time</th>
<th style="text-align: right;">Brand Attitudes</th>
<th style="text-align: right;">Age</th>
<th style="text-align: left;">Female</th>
<th style="text-align: left;">Desktop</th>
<th style="text-align: left;">Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">59e833e72f63d30001c8fb86</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">1.783</td>
<td style="text-align: right;">0.5782973</td>
<td style="text-align: right;">4.000000</td>
<td style="text-align: right;">36</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">59f226a9d6380600018b2923</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">6.393</td>
<td style="text-align: right;">1.8552036</td>
<td style="text-align: right;">5.333333</td>
<td style="text-align: right;">60</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5a0ef93279f96a0001c73f25</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">3.500</td>
<td style="text-align: right;">1.2527630</td>
<td style="text-align: right;">4.000000</td>
<td style="text-align: right;">31</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">5a42c80ddaea400001ac24e0</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">10.239</td>
<td style="text-align: right;">2.3262040</td>
<td style="text-align: right;">5.000000</td>
<td style="text-align: right;">47</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5a542b96e0cf3d0001260df1</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">1.111</td>
<td style="text-align: right;">0.1052605</td>
<td style="text-align: right;">4.000000</td>
<td style="text-align: right;">38</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">5a5c2c2eeedc320001429df1</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">20.422</td>
<td style="text-align: right;">3.0166128</td>
<td style="text-align: right;">4.000000</td>
<td style="text-align: right;">33</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5a7618b18fe2dc0001057243</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">3.866</td>
<td style="text-align: right;">1.3522204</td>
<td style="text-align: right;">6.000000</td>
<td style="text-align: right;">43</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">5a78e410ae9a0b0001a97274</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">5.915</td>
<td style="text-align: right;">1.7774915</td>
<td style="text-align: right;">6.000000</td>
<td style="text-align: right;">32</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5a91756d6475f900019f90f1</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">4.484</td>
<td style="text-align: right;">1.5005155</td>
<td style="text-align: right;">4.000000</td>
<td style="text-align: right;">43</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">5a9fc2b66475f90001a0219a</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">3.165</td>
<td style="text-align: right;">1.1521531</td>
<td style="text-align: right;">1.333333</td>
<td style="text-align: right;">31</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5aaf4b0ce1546900019b01de</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.301</td>
<td style="text-align: right;">-1.2006450</td>
<td style="text-align: right;">4.000000</td>
<td style="text-align: right;">43</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-AgarwalHosanagarSmith_2011" class="csl-entry" role="doc-biblioentry">
Agarwal, Ashish, Kartik Hosanagar, and Michael D. Smith. 2011. <span>“Location, Location, Location: An Analysis of Profitability of Position in Online Advertising Markets.”</span> <em>Journal of Marketing Research</em> 48 (6): 1057–73. <a href="https://doi.org/10.1509/jmr.08.0468">https://doi.org/10.1509/jmr.08.0468</a>.
</div>
<div id="ref-AhmadEtAl_2024" class="csl-entry" role="doc-biblioentry">
Ahmad, Wajeeha, Ananya Sen, Charles Eesley, and Erik Brynjolfsson. 2024. <span>“Companies Inadvertently Fund Online Misinformation Despite Consumer Backlash.”</span> <em>Nature</em> 630: 123–31. <a href="https://doi.org/10.1038/s41586-024-07404-1">https://doi.org/10.1038/s41586-024-07404-1</a>.
</div>
<div id="ref-BergerMoeSchweidel_2023" class="csl-entry" role="doc-biblioentry">
Berger, Jonah, Wendy W. Moe, and David A. Schweidel. 2023. <span>“What Holds Attention? Linguistic Drivers of Engagement.”</span> <em>Journal of Marketing</em> 87 (5): 793–809. <a href="https://doi.org/10.1177/00222429231152880">https://doi.org/10.1177/00222429231152880</a>.
</div>
<div id="ref-Bulmer_1979" class="csl-entry" role="doc-biblioentry">
Bulmer, M. G. 1979. <em>Principles of Statistics</em>. Dover Books on Mathematics Series. Dover Publications. <a href="https://books.google.ch/books?id=dh24EaSrmBkC">https://books.google.ch/books?id=dh24EaSrmBkC</a>.
</div>
<div id="ref-Buschschlueter_2024" class="csl-entry" role="doc-biblioentry">
Buschschlüter, Vanessa. 2024. <span>“Brazil Floods: ’We’ve Never Experienced Anything Like It’.”</span> BBC News. <a href="https://web.archive.org/web/20240805170342/https://www.bbc.com/news/articles/cle07g0zzqeo">https://web.archive.org/web/20240805170342/https://www.bbc.com/news/articles/cle07g0zzqeo</a>.
</div>
<div id="ref-CampbellKeller_2003" class="csl-entry" role="doc-biblioentry">
Campbell, Margaret C., and Kevin Lane Keller. 2003. <span>“<span class="nocase">Brand Familiarity and Advertising Repetition Effects</span>.”</span> <em>Journal of Consumer Research</em> 30 (2): 292–304. <a href="https://doi.org/10.1086/376800">https://doi.org/10.1086/376800</a>.
</div>
<div id="ref-FournierSrinivasan_2023" class="csl-entry" role="doc-biblioentry">
Fournier, Susan, and Shuba Srinivasan. 2023. <span>“Monitoring Marketing Sources of Brand Reputation Risk.”</span> <em>NIM Marketing Intelligence Review</em> 15 (1): 46–53. <a href="https://doi.org/doi:10.2478/nimmir-2023-0007">https://doi.org/doi:10.2478/nimmir-2023-0007</a>.
</div>
<div id="ref-GumGum_2017" class="csl-entry" role="doc-biblioentry">
GumGum Inc. 2017. <span>“The New Brand Safety Crisis: A Fractured Environment.”</span> GumGum. <a href="https://web.archive.org/web/20220317063148/https://insights.gumgum.com/hubfs/Brand_Safety_GumGum.pdf">https://web.archive.org/web/20220317063148/https://insights.gumgum.com/hubfs/Brand_Safety_GumGum.pdf</a>.
</div>
<div id="ref-Instagram_2020" class="csl-entry" role="doc-biblioentry">
Instagram. 2020. <span>“Instagram Year in Review: How Memes Were the Mood of 2020.”</span> <a href="https://web.archive.org/web/20240731100452/https://about.instagram.com/blog/announcements/instagram-year-in-review-how-memes-were-the-mood-of-2020/">https://web.archive.org/web/20240731100452/https://about.instagram.com/blog/announcements/instagram-year-in-review-how-memes-were-the-mood-of-2020/</a>.
</div>
<div id="ref-KerwinRostomSterck_2024" class="csl-entry" role="doc-biblioentry">
Kerwin, Jason, Nada Rostom, and Olivier Sterck. 2024. <span>“Striking the Right Balance: Why Standard Balance Tests over-Reject the Null, and How to Fix It.”</span> IZA Discussion Paper 17217. Institute of Labor Economics (IZA). <a href="https://www.iza.org/publications/dp/17217/striking-the-right-balance-why-standard-balance-tests-over-reject-the-null-and-how-to-fix-it">https://www.iza.org/publications/dp/17217/striking-the-right-balance-why-standard-balance-tests-over-reject-the-null-and-how-to-fix-it</a>.
</div>
<div id="ref-MalodiaEtAl_2022" class="csl-entry" role="doc-biblioentry">
Malodia, Suresh, Amandeep Dhir, Anil Bilgihan, Pranao Sinha, and Tanishka Tikoo. 2022. <span>“Meme Marketing: How Can Marketers Drive Better Engagement Using Viral Memes?”</span> <em>Psychology &amp; Marketing</em> 39 (9): 1775–1801. <a href="https://doi.org/10.1002/mar.21702">https://doi.org/10.1002/mar.21702</a>.
</div>
<div id="ref-MurphyHofackerMizerski_2006" class="csl-entry" role="doc-biblioentry">
Murphy, Jamie, Charles Hofacker, and Richard Mizerski. 2006. <span>“Primacy and Recency Effects on Clicking Behavior.”</span> <em>Journal of Computer-Mediated Communication</em> 11 (2): 522–35. <a href="https://doi.org/10.1111/j.1083-6101.2006.00025.x">https://doi.org/10.1111/j.1083-6101.2006.00025.x</a>.
</div>
<div id="ref-Ordenes_2019" class="csl-entry" role="doc-biblioentry">
Ordenes, Francisco Villarroel, Dhruv Grewal, Stephan Ludwig, Ko De Ruyter, Dominik Mahr, and Martin Wetzels. 2019. <span>“Cutting Through Content Clutter: How Speech and Image Acts Drive Consumer Sharing of Social Media Brand Messages.”</span> <em>Journal of Consumer Research</em> 45 (5): 988–1012. <a href="https://doi.org/10.1093/jcr/ucy032">https://doi.org/10.1093/jcr/ucy032</a>.
</div>
<div id="ref-Porter_2021" class="csl-entry" role="doc-biblioentry">
Porter, Jonathan. 2021. <span>“Commentary: Inefficiencies in Digital Advertising Markets: Evidence from the Field.”</span> <em>Journal of Marketing</em> 85 (1): 30–34. <a href="https://doi.org/10.1177/0022242920970133">https://doi.org/10.1177/0022242920970133</a>.
</div>
<div id="ref-SimonovVallettiVeiga_2024" class="csl-entry" role="doc-biblioentry">
Simonov, Andrey, Tommaso Valletti, and Andre Veiga. 2024. <span>“Attention Spillovers from News to Ads: Evidence from an Eye-Tracking Experiment.”</span> <em>Journal of Marketing Research</em> 0 (0): 00222437241256900. <a href="https://doi.org/10.1177/00222437241256900">https://doi.org/10.1177/00222437241256900</a>.
</div>
<div id="ref-SimonsohnEtAl_2024" class="csl-entry" role="doc-biblioentry">
Simonsohn, Uri, Andres Montealegre, and Ioannis Evangelidis. 2024. <span>“Stimulus Sampling Reimagined: Designing Experiments with Mix-and-Match, Analyzing Results with Stimulus Plots,”</span> February. <a href="https://doi.org/10.2139/ssrn.4716832">https://doi.org/10.2139/ssrn.4716832</a>.
</div>
<div id="ref-WedelPieters_2000" class="csl-entry" role="doc-biblioentry">
Wedel, Michel, and Rik Pieters. 2000. <span>“Eye Fixations on Advertisements and Memory for Brands: A Model and Findings.”</span> <em>Marketing Science</em> 19 (4): 297–312. <a href="https://doi.org/10.1287/mksc.19.4.297.11794">https://doi.org/10.1287/mksc.19.4.297.11794</a>.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>This expectation is based on each of the 5 sponsored posts being shown once per participant (N=300) in a feed of 40 positions, leading to an average of <span class="math inline">\(\frac{300}{40} = 7.5\)</span> for each brand’s ad placement across all positions.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./stimuli.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Stimuli</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>